// ── COURSE CATALOG ───────────────────────────────────
// 255 courses across CSE, EEE, BBA, ECO, ENG, ARC, PHR, LAW.

import { DEPARTMENTS } from './departments.js';

// ── COMPREHENSIVE BRACU COURSE CATALOG ───────────────
    // Covers CSE, EEE, BBA, ECO, ENG, LAW, PHR, ARC, BIO, CHE + GED
    const COURSE_DB = {};
    const _CATALOG = [
      // ── GED / Common ─────────────────────────────────
      ['BNG103','Bangla Language and Literature',3],
      ['EMB101','Emergence of Bangladesh',3],
      ['ENG101','Fundamentals of English',3],
      ['ENG102','English Composition I',3],
      ['HUM103','Ethics and Culture',3],
      ['MAT092','Remedial Course in Mathematics',0],
      ['PHY111','Principles of Physics I',3],
      ['PHY112','Principles of Physics II',3],
      ['MAT110','Mathematics I: Differential Calculus & Coordinate Geometry',3],
      ['MAT120','Mathematics II: Integral Calculus & Differential Equations',3],
      ['MAT215','Mathematics III: Complex Variables & Laplace Transformations',3],
      ['STA201','Elements of Statistics and Probability',3],
      ['SOC101','Introduction to Sociology',3],
      ['POL101','Introduction to Political Science',3],
      ['ECO101','Principles of Microeconomics',3],
      ['ECO102','Principles of Macroeconomics',3],
      // ── CSE ──────────────────────────────────────────
      ['CSE110','Programming Language I',3],
      ['CSE111','Programming Language II',3],
      ['CSE220','Data Structures',3],
      ['CSE221','Algorithms',3],
      ['CSE230','Discrete Mathematics',3],
      ['CSE250','Computer Organization and Architecture',3],
      ['CSE251','Digital Logic Design',3],
      ['CSE260','Database Systems',3],
      ['CSE310','Operating Systems',3],
      ['CSE320','Computer Networks',3],
      ['CSE330','Software Engineering',3],
      ['CSE340','Theory of Computation',3],
      ['CSE341','Programming Language Concepts',3],
      ['CSE350','Computer Graphics',3],
      ['CSE360','Artificial Intelligence',3],
      ['CSE361','Machine Learning',3],
      ['CSE370','Computer Security',3],
      ['CSE400','Computer Science and Engineering Project',3],
      ['CSE401','Computer Science and Engineering Thesis',6],
      ['CSE410','Compiler Design',3],
      ['CSE420','Microprocessor and Assembly Language',3],
      ['CSE421','Embedded Systems',3],
      ['CSE422','Internet of Things',3],
      ['CSE425','VLSI Design',3],
      ['CSE430','Numerical Methods',3],
      ['CSE431','Simulation and Modeling',3],
      ['CSE432','High Performance Computing',3],
      ['CSE440','Software Project Management',3],
      ['CSE445','Human Computer Interaction',3],
      ['CSE446','Mobile Application Development',3],
      ['CSE447','Web Technologies',3],
      ['CSE450','Computer Vision',3],
      ['CSE451','Natural Language Processing',3],
      ['CSE452','Deep Learning',3],
      ['CSE460','Information Retrieval',3],
      ['CSE461','Data Mining',3],
      ['CSE465','Bioinformatics',3],
      ['CSE470','Cryptography',3],
      ['CSE471','Network Security',3],
      ['CSE480','Game Development',3],
      ['CSE483','Cloud Computing',3],
      ['CSE484','Distributed Systems',3],
      ['CSE490','Special Topics in CSE',3],
      ['CSE499','Senior Design Project',3],
      // ── EEE ──────────────────────────────────────────
      ['EEE101','Introduction to Electrical Engineering',3],
      ['EEE102','Electrical Circuits I',3],
      ['EEE201','Electrical Circuits II',3],
      ['EEE202','Electronic Devices and Circuits I',3],
      ['EEE203','Electronic Devices and Circuits II',3],
      ['EEE204','Signals and Systems',3],
      ['EEE205','Electromagnetic Fields and Waves',3],
      ['EEE206','Engineering Mathematics',3],
      ['EEE210','Digital Electronics',3],
      ['EEE211','Electrical Machines I',3],
      ['EEE212','Electrical Machines II',3],
      ['EEE301','Control Systems',3],
      ['EEE302','Communication Theory',3],
      ['EEE303','Microprocessors and Interfacing',3],
      ['EEE304','Digital Signal Processing',3],
      ['EEE305','Power Electronics',3],
      ['EEE306','Power Systems I',3],
      ['EEE307','Power Systems II',3],
      ['EEE311','VLSI Design',3],
      ['EEE312','Antenna and Wave Propagation',3],
      ['EEE313','Wireless Communications',3],
      ['EEE401','Fiber Optic Communications',3],
      ['EEE402','Satellite Communications',3],
      ['EEE403','Digital Communications',3],
      ['EEE404','Computer Networks for EEE',3],
      ['EEE405','Robotics and Automation',3],
      ['EEE406','Renewable Energy Systems',3],
      ['EEE411','Industrial Instrumentation',3],
      ['EEE412','Biomedical Engineering',3],
      ['EEE413','High Voltage Engineering',3],
      ['EEE421','EEE Project',3],
      ['EEE422','EEE Thesis',6],
      ['EEE430','Image Processing',3],
      ['EEE431','Machine Learning for Engineers',3],
      ['EEE490','Special Topics in EEE',3],
      // ── BBA ──────────────────────────────────────────
      ['ACC101','Introduction to Financial Accounting',3],
      ['ACC201','Introduction to Management Accounting',3],
      ['ACC301','Intermediate Accounting I',3],
      ['ACC302','Intermediate Accounting II',3],
      ['ACC303','Advanced Accounting',3],
      ['ACC311','Cost and Management Accounting',3],
      ['ACC401','Auditing and Assurance',3],
      ['ACC402','Taxation',3],
      ['BUS101','Introduction to Business',3],
      ['BUS102','Business Communication',3],
      ['BUS201','Business Statistics',3],
      ['BUS202','Business Mathematics',3],
      ['BUS211','Business Law',3],
      ['BUS301','Entrepreneurship and Innovation',3],
      ['BUS302','Research Methods in Business',3],
      ['BUS401','Business Policy and Strategy',3],
      ['BUS499','BBA Internship',3],
      ['ECO201','Intermediate Microeconomics',3],
      ['ECO211','Intermediate Macroeconomics',3],
      ['ECO212','Bangladesh Economy',3],
      ['ECO301','Managerial Economics',3],
      ['ECO311','International Economics',3],
      ['ECO321','Development Economics',3],
      ['ECO331','Monetary Economics',3],
      ['FIN201','Principles of Finance',3],
      ['FIN301','Financial Management',3],
      ['FIN302','Investment Analysis and Portfolio Management',3],
      ['FIN303','Financial Markets and Institutions',3],
      ['FIN311','Corporate Finance',3],
      ['FIN312','International Finance',3],
      ['FIN401','Advanced Financial Management',3],
      ['HRM301','Human Resource Management',3],
      ['HRM302','Organizational Behavior',3],
      ['HRM303','Compensation Management',3],
      ['HRM401','Strategic HRM',3],
      ['MGT101','Principles of Management',3],
      ['MGT201','Organizational Theory and Design',3],
      ['MGT301','Operations Management',3],
      ['MGT302','Project Management',3],
      ['MGT401','Supply Chain Management',3],
      ['MKT201','Principles of Marketing',3],
      ['MKT301','Consumer Behavior',3],
      ['MKT302','Marketing Research',3],
      ['MKT303','Advertising and Promotion',3],
      ['MKT401','Strategic Marketing',3],
      ['MKT402','Digital Marketing',3],
      ['MKT403','International Marketing',3],
      // ── English ───────────────────────────────────────
      ['ENG111','Introduction to Literature',3],
      ['ENG121','Introduction to Linguistics',3],
      ['ENG201','British Literature I',3],
      ['ENG202','British Literature II',3],
      ['ENG211','American Literature',3],
      ['ENG212','World Literature in English',3],
      ['ENG221','Introduction to Language Studies',3],
      ['ENG222','Phonetics and Phonology',3],
      ['ENG223','Morphology and Syntax',3],
      ['ENG224','Semantics and Pragmatics',3],
      ['ENG225','Sociolinguistics',3],
      ['ENG226','Psycholinguistics',3],
      ['ENG301','Literary Theory and Criticism',3],
      ['ENG302','Postcolonial Literature',3],
      ['ENG303','South Asian Literature',3],
      ['ENG304','Bangladesh Literature in English',3],
      ['ENG311','Applied Linguistics',3],
      ['ENG312','Language Acquisition',3],
      ['ENG313','Discourse Analysis',3],
      ['ENG314','English for Specific Purposes',3],
      ['ENG401','Advanced Literary Studies',3],
      ['ENG411','Research Methods',3],
      ['ENG412','ELT Methodology',3],
      ['ENG421','Creative Writing',3],
      ['ENG422','Translation Studies',3],
      ['ENG431','English Thesis',6],
      // ── Law ───────────────────────────────────────────
      ['LAW101','Legal System of Bangladesh',3],
      ['LAW111','Law of Contract',3],
      ['LAW201','Constitutional Law',3],
      ['LAW211','Law of Tort',3],
      ['LAW221','Criminal Law',3],
      ['LAW222','Evidence Law',3],
      ['LAW301','Administrative Law',3],
      ['LAW302','Company Law',3],
      ['LAW311','Civil Procedure Code',3],
      ['LAW312','Criminal Procedure Code',3],
      ['LAW321','Land Law',3],
      ['LAW322','Family Law',3],
      ['LAW331','International Law',3],
      ['LAW332','Intellectual Property Law',3],
      ['LAW333','Environmental Law',3],
      ['LAW401','Jurisprudence',3],
      ['LAW411','Arbitration and Alternative Dispute Resolution',3],
      ['LAW412','Banking Law',3],
      ['LAW421','Tax Law',3],
      ['LAW422','Labour Law',3],
      ['LAW431','Moot Court and Legal Drafting',3],
      ['LAW432','Human Rights Law',3],
      // ── Pharmacy ─────────────────────────────────────
      ['PHR101','Pharmaceutics I',3],
      ['PHR102','Pharmaceutical Chemistry I',3],
      ['PHR103','Human Anatomy and Physiology I',3],
      ['PHR104','Human Anatomy and Physiology II',3],
      ['PHR201','Pharmaceutics II',3],
      ['PHR202','Pharmaceutical Chemistry II',3],
      ['PHR203','Pharmacology I',3],
      ['PHR204','Pharmacology II',3],
      ['PHR211','Microbiology',3],
      ['PHR212','Biochemistry',3],
      ['PHR301','Pharmaceutical Analysis',3],
      ['PHR302','Clinical Pharmacy',3],
      ['PHR303','Industrial Pharmacy',3],
      ['PHR311','Pharmacokinetics',3],
      ['PHR312','Toxicology',3],
      ['PHR321','Biotechnology',3],
      ['PHR322','Pharmaceutical Microbiology',3],
      ['PHR331','Pharmacy Practice',3],
      ['PHR332','Drug Regulatory Affairs',3],
      ['PHR401','Pharmaceutical Research',3],
      ['PHR402','Pharmacoeconomics',3],
      ['PHR403','Pharmacy Thesis',6],
      // ── Architecture ─────────────────────────────────
      ['ARC101','Architectural Design Studio I',6],
      ['ARC102','Architectural Design Studio II',6],
      ['ARC111','History of Architecture I',3],
      ['ARC112','History of Architecture II',3],
      ['ARC121','Architectural Graphics',3],
      ['ARC122','Building Construction I',3],
      ['ARC201','Architectural Design Studio III',6],
      ['ARC202','Architectural Design Studio IV',6],
      ['ARC211','History of Architecture III',3],
      ['ARC212','Urban Design',3],
      ['ARC221','Building Construction II',3],
      ['ARC222','Building Structures I',3],
      ['ARC301','Architectural Design Studio V',6],
      ['ARC302','Architectural Design Studio VI',6],
      ['ARC311','Building Services',3],
      ['ARC312','Environmental Science in Architecture',3],
      ['ARC321','Professional Practice',3],
      ['ARC322','Landscape Architecture',3],
      ['ARC331','Building Structures II',3],
      ['ARC401','Architectural Design Studio VII',6],
      ['ARC402','Architectural Design Studio VIII',6],
      ['ARC411','Architecture Thesis Project',12],
      // ── Biotechnology ─────────────────────────────────
      ['BIO101','Introduction to Biology',3],
      ['BIO102','Cell Biology',3],
      ['BIO201','Genetics',3],
      ['BIO202','Molecular Biology',3],
      ['BIO203','Biochemistry for Biotech',3],
      ['BIO204','Microbiology for Biotech',3],
      ['BIO301','Genetic Engineering',3],
      ['BIO302','Immunology',3],
      ['BIO303','Bioinformatics',3],
      ['BIO401','Biotechnology Thesis',6],
      // ── Chemical Engineering ──────────────────────────
      ['CHE101','Introduction to Chemical Engineering',3],
      ['CHE102','Chemistry I',3],
      ['CHE103','Chemistry II',3],
      ['CHE201','Chemical Engineering Thermodynamics',3],
      ['CHE202','Fluid Mechanics',3],
      ['CHE203','Heat Transfer',3],
      ['CHE301','Mass Transfer',3],
      ['CHE302','Chemical Reaction Engineering',3],
      ['CHE303','Process Control',3],
      ['CHE401','Plant Design',3],
      ['CHE402','Chemical Engineering Thesis',6],
    ];
    _CATALOG.forEach(([code, name, credits]) => {
      const full = `${name} (${code})`;
      COURSE_DB[code] = { code, name, credits, full };
    });
    // Also pull in any preset courses not already in catalog
    Object.values(DEPARTMENTS).forEach(dept => {
      dept.presets.forEach(sem => {
        sem.courses.forEach(c => {
          const match = c.name.match(/\(([A-Z]{2,4}\d{3}[A-Z]?)\)$/);
          const code  = match ? match[1] : '';
          const name  = c.name.replace(/\s*\([^)]+\)$/, '').trim();
          if (code && !COURSE_DB[code]) {
            COURSE_DB[code] = { code, name, credits: c.credits, full: c.name };
          }
        });
      });
    });
    const ALL_COURSES = Object.values(COURSE_DB).sort((a,b) => a.code.localeCompare(b.code));

    let currentDept = '';

    // ── AUTOCOMPLETE LOGIC ────────────────────────────────
    const portal = document.getElementById('suggestions-portal');
    let activeInput = null;

export { COURSE_CATALOG };