import { DEPARTMENTS } from './departments.js';

export const COURSE_DB = {};

const _CATALOG = [
  // ── GED / Common ─────────────────────────────────
  ['ANT101','Introduction to Anthropology',3],
  ['ANT201','Anthropology of Corporate Culture',3],
  ['ANT202','Social Inequality',3],
  ['ANT342','Body and Society',3],
  ['ANT351','Gender and Development',3],
  ['BNG103','Bangla Language and Literature',3],
  ['CST301','For the Love of Food',3],
  ['CST302','The Pursuit of Wellbeing',3],
  ['CST303','The Pursuit of Justice',3],
  ['CST304','Creating Documentaries',3],
  ['CST305','Inhabiting and Building Our World',3],
  ['ECO101','Principles of Microeconomics',3],
  ['ECO102','Principles of Macroeconomics',3],
  ['ECO105','Fundamentals of Economics',3],
  ['EMB101','Emergence of Bangladesh',3],
  ['ENG091','Foundation Course in English',0],
  ['ENG101','Fundamentals of English',3],
  ['ENG102','English Composition I',3],
  ['ENG103','Advanced Writing Skills and Presentation',3],
  ['ENG110','English for Life',3],
  ['ENG113','Introduction to English Poetry',3],
  ['ENG114','Introduction to English Drama',3],
  ['ENG115','Introduction to English Prose',3],
  ['ENG203','Communication Skills',1.5],
  ['ENG333','Globalization and the Media',3],
  ['ENV103','Introduction to Environmental Science',3],
  ['HST102','The Modern World',3],
  ['HST103','History of Bangladesh',3],
  ['HUM101','World Civilization and Culture',3],
  ['HUM102','Introduction to Philosophy',3],
  ['HUM103','Ethics and Culture',3],
  ['MAT092','Remedial Course in Mathematics',0],
  ['MAT101','Fundamentals of Mathematics',3],
  ['MAT110','Mathematics I: Differential Calculus & Coordinate Geometry',3],
  ['MAT120','Mathematics II: Integral Calculus & Differential Equations',3],
  ['MAT215','Mathematics III: Complex Variables & Laplace Transformations',3],
  ['PHY101','Introduction to Physics',3],
  ['PHY111','Principles of Physics I',3],
  ['PHY112','Principles of Physics II',3],
  ['POL101','Introduction to Political Science',3],
  ['PSY101','Introduction to Psychology',3],
  ['SOC101','Introduction to Sociology',3],
  ['STA101','Introduction to Statistics',3],
  ['STA201','Elements of Statistics and Probability',3],
  // ── CSE ──────────────────────────────────────────
  ['CSE101','Introduction to Computer Science',3],
  ['CSE103','Introduction to Computing',3],
  ['CSE110','Programming Language I',3],
  ['CSE111','Programming Language-II',3],
  ['CSE220','Data Structures',3],
  ['CSE221','Algorithms',3],
  ['CSE230','Discrete Mathematics',3],
  ['CSE250','Circuits and Electronics',3],
  ['CSE260','Digital Logic Design',3],
  ['CSE310','Object Oriented Programming',3],
  ['CSE320','Data Communications',3],
  ['CSE321','Operating Systems',3],
  ['CSE330','Numerical Methods',3],
  ['CSE331','Automata and Computability',3],
  ['CSE340','Computer Architecture',3],
  ['CSE341','Microprocessors',3],
  ['CSE350','Digital Electronics and Pulse Techniques',3],
  ['CSE360','Computer Interfacing',3],
  ['CSE370','Database Systems',3],
  ['CSE390','Technical Communication',3],
  ['CSE391','Programming for the Internet',3],
  ['CSE400','Project & Thesis',4],
  ['CSE402','Optimization',3],
  ['CSE420','Compiler Design',3],
  ['CSE421','Computer Networks',3],
  ['CSE422','Artificial Intelligence',3],
  ['CSE423','Computer Graphics',3],
  ['CSE424','Pattern Recognition',3],
  ['CSE425','Neural Networks',3],
  ['CSE426','Advanced Algorithms',3],
  ['CSE427','Machine Learning',3],
  ['CSE428','Image Processing',3],
  ['CSE437','Data Science: Coding with Real World Data',3],
  ['CSE440','Natural Language Processing II',3],
  ['CSE443','Bioinformatics I',3],
  ['CSE446','Blockchain and Cryptocurrencies',3],
  ['CSE447','Cryptography and Cryptoanalysis',3],
  ['CSE449','Parallel, Distributed, and High-Performance Computing (HPC)',3],
  ['CSE460','VLSI Design',3],
  ['CSE461','Introduction to Robotics',3],
  ['CSE463','Computer Vision: Fundamentals and Applications',3],
  ['CSE470','Software Engineering',3],
  ['CSE471','System Analysis and Design',3],
  ['CSE472','Human Computer Interface',3],
  ['CSE481','Quantum Computing I',3],
  ['CSE482','Quantum Computing II',3],
  ['CSE489','Android App Development',3],
  ['CSE490A','Gamification: Engineering User Engagement',3],
  ['CSE490B','Introduction to Cybersecurity',3],
  ['CSE490C','Quantum Computing III',3],
  ['CSE490D','Introduction to Football Data and Analytics',3],
  // ── EEE ──────────────────────────────────────────
  ['EEE101','Electrical Circuits I',3],
  ['EEE103','Computer Programming',3],
  ['EEE203','Electrical Circuits II',3],
  ['EEE205','Electronic Circuits I',3],
  ['EEE221','Energy Conversion I',3],
  ['EEE241','Electromagnetic Waves and Fields',3],
  ['EEE243','Signals and Systems',3],
  ['EEE282','Numerical Techniques',3],
  ['EEE283','Digital Logic Design',3],
  ['EEE301','Digital Electronics',3],
  ['EEE302','Digital Electronics Laboratory',1.5],
  ['EEE305','Control Systems',3],
  ['EEE308','Electronic Circuits II',3],
  ['EEE309','Semiconductor Device Physics',3],
  ['EEE321','Power System I',3],
  ['EEE341','Introduction to Communication Engineering',3],
  ['EEE343','Digital Signal Processing',3],
  ['EEE345','Electrical Services',3],
  ['EEE359','Engineering Project Management',3],
  ['EEE361','Data Communications',3],
  ['EEE365','Microprocessors',3],
  ['EEE366','Microprocessors Laboratory',1.5],
  ['EEE369','Professional Practice, Engineers and Society',3],
  ['EEE373','Embedded System Design',3],
  ['EEE382','Modelling and Simulation',3],
  ['EEE383','Electronic System Design',3],
  ['EEE384','Electrical Service Design',3],
  ['EEE385','Machine Learning',3],
  ['EEE403','Properties of Electronic Materials',3],
  ['EEE410','Computer Architecture',3],
  ['EEE411','VLSI Design',3],
  ['EEE412','VLSI Design Laboratory',1.5],
  ['EEE415','Analog Integrated Circuit Design',3],
  ['EEE421','Power Electronics',3],
  ['EEE433','Power System II',3],
  ['EEE435','Renewable Energy Systems',3],
  ['EEE445','Digital Communications',3],
  ['EEE465','Computer Networks',3],
  ['EEE472','Artificial Intelligence',3],
  ['EEE474','Neural Networks',3],
  ['EEE476','Image Processing',3],
  ['EEE498','Directed Research',3],
  // ── BBA — Accounting ────────────────────────────
  ['ACT201','Financial Accounting',3],
  ['ACT202','Management Accounting',3],
  ['ACT301','Intermediate Accounting',3],
  ['ACT421','Accounting Information System',3],
  ['ACT422','Cost Accounting',3],
  ['ACT423','Fundamentals of Taxation',3],
  ['ACT427','Auditing and Assurance',3],
  ['ACT429','Financial Statement Analysis',3],
  ['ACT431','Advanced Accounting',3],
  ['ACT432','International Accounting',3],
  ['ACT435','Accounting for Governmental and Non-Profit Organizations',3],
  ['ACT438','Accounting Theory and Practices',3],
  ['ACT471','Special Issues in Accounting',3],
  // ── BBA — Business ─────────────────────────────
  ['BUS102','Business - Basics, Ethics and Environment',3],
  ['BUS201','Business Communication',3],
  ['BUS204','Business Law and Corporate Governance',3],
  ['BUS209','Quantitative Methods for Business',3],
  ['BUS301','International Business',3],
  ['BUS302','Research Methods and Business Analytics',3],
  ['BUS321','Principles of Entrepreneurship',3],
  ['BUS400','Internship/Thesis',4],
  ['BUS421','Venture Development',3],
  ['BUS422','Small Business Management',3],
  ['BUS423','Business Plan Development',3],
  ['BUS471','Special Issues in Entrepreneurship',3],
  // ── BBA — Finance ──────────────────────────────
  ['FIN201','Financial Environment and Banking',3],
  ['FIN301','Financial Management',3],
  ['FIN421','Corporate Finance',3],
  ['FIN422','Fundamentals of Investments',3],
  ['FIN423','Security Analysis and Portfolio Management',3],
  ['FIN425','International Financial Management',3],
  ['FIN428','Real Estate Finance',3],
  ['FIN431','Introduction to Financial Derivatives',3],
  ['FIN432','Mergers and Acquisition and Corporate Restructuring',3],
  ['FIN433','Financial Modeling',3],
  ['FIN441','Bank Management and Digital Banking',3],
  ['FIN461','Insurance and Risk Management',3],
  ['FIN471','Special Issues in Finance',3],
  // ── BBA — Management ───────────────────────────
  ['MGT213','Management Practices and Organizational Behavior',3],
  ['MGT301','Human Resource Management',3],
  ['MGT401','Strategic Management',3],
  ['MGT421','Leadership and Ethics',3],
  ['MGT422','Compensation Management',3],
  ['MGT423','Training and Development',3],
  ['MGT424','Employee and Labor Relations',3],
  ['MGT425','Manpower Planning and Forecasting',3],
  ['MGT427','Strategic Human Resource Management',3],
  ['MGT431','Industrial Psychology',3],
  ['MGT432','International and Comparative HRM',3],
  ['MGT433','Conflict Management and Negotiation Tactics in Workplace',3],
  ['MGT434','Performance Management',3],
  ['MGT435','Occupational Health, Safety and Employee Well Being',3],
  ['MGT436','Managing Culture, Organizational Change and Innovation',3],
  ['MGT437','Human Resource Analytics and Applications',3],
  ['MGT471','Special Issues in Human Resource Management',3],
  // ── BBA — Marketing ────────────────────────────
  ['MKT201','Principles of Marketing',3],
  ['MKT301','Marketing Management',3],
  ['MKT421','Consumer Behavior',3],
  ['MKT422','Sales Management',3],
  ['MKT423','Brand Management',3],
  ['MKT425','International Marketing',3],
  ['MKT426','Marketing Research',3],
  ['MKT428','Strategic Marketing',3],
  ['MKT431','Services Marketing',3],
  ['MKT433','Integrated Marketing Communication',3],
  ['MKT434','Customer Relationship Management',3],
  ['MKT435','Marketing Analytics',3],
  ['MKT471','Special Issues in Marketing',3],
  // ── BBA — MIS / Operations / E-Business ────────
  ['MSC221','Computer Applications in Business',3],
  ['MSC301','Production and Operations Management',3],
  ['MSC321','Management Information Systems',3],
  ['MSC422','Total Quality Management',3],
  ['MSC423','Introduction to Supply Chain Management',3],
  ['MSC424','Operations Research (Quantitative Methods for Decision Making)',3],
  ['MSC425','Material Management',3],
  ['MSC427','Demand Planning and Fulfillment',3],
  ['MSC429','Services Management',3],
  ['MSC433','Lean Six Sigma',3],
  ['MSC434','Green Supply Chain Management',3],
  ['MSC435','Sustainable Procurement and Outsourcing',3],
  ['MSC441','Introduction to Electronic Commerce',3],
  ['MSC442','Information Technology',3],
  ['MSC443','Applied Database Management',3],
  ['MSC444','Systems Analysis',3],
  ['MSC445','Management of Information Systems',3],
  ['MSC446','Marketing on the Internet',3],
  ['MSC447','Technology Fundamentals of Electronic Commerce',3],
  ['MSC448','Management of Online Business',3],
  ['MSC449','Business Data Communications',3],
  ['MSC451','Local Area Network Administration',3],
  ['MSC452','E-Commerce Programming',3],
  ['MSC453','Distributed Information Systems for Business',3],
  ['MSC454','Managing E-Commerce Projects',3],
  ['MSC456','E-Commerce Infrastructure',3],
  ['MSC457','E-Commerce Risk and Security Management',3],
  ['MSC459','Designing Web Usability',3],
  ['MSC471','Special Issues in E-Business',3],
  ['MSC472','Special Issues in Information Management',3],
  ['MSC473','Special Issues in Operations and Supply Chain Management',3],
  // ── Economics ───────────────────────────────────
  // ECO101, ECO102, ECO105 are in GED section
  ['ECO201','Mathematics for Business and Economics',3],
  ['ECO202','Statistical Methods for Business and Economics',3],
  ['ECO206','Intermediate Microeconomics I',3],
  ['ECO207','Intermediate Macroeconomics I',3],
  ['ECO208','Intermediate Microeconomics II',3],
  ['ECO209','Intermediate Macroeconomics II',3],
  ['ECO301','Microeconomic Analysis',3],
  ['ECO302','Macroeconomic Analysis',3],
  ['ECO303','Introduction to Econometrics',3],
  ['ECO304','Agricultural Economics',3],
  ['ECO305','Labour Economics',3],
  ['ECO306','Urban Economics',3],
  ['ECO307','Mathematical Methods for Economics',3],
  ['ECO308','International Trade',3],
  ['ECO309','Public Finance',3],
  ['ECO310','History of Economic Thought',3],
  ['ECO311','Economic Growth and Development',3],
  ['ECO312','Cost Benefit Analysis',3],
  ['ECO313','Environmental and Resource Economics',3],
  ['ECO322','Gender and Development',3],
  ['ECO323','Health Economics',3],
  ['ECO324','Bangladesh Economy',3],
  ['ECO325','Political Economic Analysis',3],
  ['ECO331','Corporate Economics and Finance',3],
  ['ECO401','Research Methods in Economics and Social Sciences',3],
  ['ECO421','Welfare Economics and Development',3],
  ['ECO422','Human Capital and Development',3],
  ['ECO430','Econometric Analysis',3],
  ['ECO431','International Finance and Economic Policy',3],
  ['ECO432','Money and Banking',3],
  ['ECO491','Introduction to Game Theory',3],
  ['ECO492','Advanced Mathematical Economics',3],
  ['ECO493','Industrial Organization',3],
  ['ECO494','Open Economy Macroeconomics',3],
  ['ECO498','Independent Study',3],
  ['ECO499','Undergraduate Thesis',3],
  // ── English (ENH) ────────────────────────────────
  // ENG091,101,102,103,110,113-115,203,333 are in GED section
  ['ENG111','Introduction to Linguistics',3],
  ['ENG205','Introduction to Media Studies',3],
  ['ENG211','Sociolinguistics',3],
  ['ENG212','Psycholinguistics',3],
  ['ENG213','Survey of English Literature I',3],
  ['ENG214','Survey of English Literature II',3],
  ['ENG215','Survey of English Literature III',3],
  ['ENG217','Shakespeare',3],
  ['ENG218','Post-Colonial Writing in English',3],
  ['ENG220','Creative Writing',3],
  ['ENG221','Discourse Analysis',3],
  ['ENG222','Popular Literature',3],
  ['ENG242','The Study of English',3],
  ['ENG301','Research Methodology',3],
  ['ENG310','Feminism and Feminist Works and Women Writers in Bangla Literature',3],
  ['ENG311','Post-colonial Bangla Literature',3],
  ['ENG312','Bangla Literature: First Phase of Modernism',3],
  ['ENG315','First Language Acquisition',3],
  ['ENG319','Modernism',3],
  ['ENG320','Arts and Visual Literacy',3],
  ['ENG327','Second Language Acquisition',3],
  ['ENG328','Advanced Grammar',3],
  ['ENG330','Educational Theories',3],
  ['ENG331','Cultural Studies',3],
  ['ENG332','Teaching Techniques',3],
  ['ENG334','ELT Methodology',3],
  ['ENG335','Linguistic Theories',3],
  ['ENG343','Classical Literary Theory',3],
  ['ENG354','Survey of American Literature I',3],
  ['ENG355','Survey of American Literature II',3],
  ['ENG358','Survey of World Literature in Translation II',3],
  ['ENG362','The English Text in the Bengali / Colonial Classroom',3],
  ['ENG366','Major Texts of the Feminist Tradition in the West',3],
  ['ENG367','English Writing and British Colonialism',3],
  ['ENG401','Editing',3],
  ['ENG404','Copywriting',3],
  ['ENG408','Introduction to Syntax',3],
  ['ENG409','Introduction to Semantics',3],
  ['ENG410','Introduction to Neurolinguistics',3],
  ['ENG411','Stylistics: Teaching Language Through Literature',3],
  ['ENG412','Second Phase of Modernism: Post-War Bangla Literature',3],
  ['ENG414','Twentieth-Century English Literature',3],
  ['ENG415','Twentieth Century Poetry',3],
  ['ENG416','World Epics',3],
  ['ENG422','The Urban Novel',3],
  ['ENG425','Language Delay and Disorders in Children',3],
  ['ENG434','Material Design',3],
  ['ENG437','Testing and Evaluation',3],
  ['ENG438','Syllabus Design',3],
  ['ENG439','Teaching Practicum',3],
  ['ENG440','English for the Print Media',3],
  ['ENG461','Modern Drama',3],
  ['ENG463','Theories of Fiction',3],
  ['ENG465','Translation Studies',3],
  ['ENG480','Independent Reading Course',3],
  ['ENG490','Seminar Course',3],
  // ── Law ───────────────────────────────────────────
  ['LAW101','The Jurisprudence of Legal Concepts',3],
  ['LAW102','Obligations: Contract Law',3],
  ['LAW103','Delict: Law of Tort',3],
  ['LAW104','Constitutional Law',3],
  ['LAW201','Equitable Principles and Specific Relief',3],
  ['LAW202','Muslim Family Law and Reforms',3],
  ['LAW203','Property Law and Transfer',3],
  ['LAW204','Law of Registration and Limitation',3],
  ['LAW205','Business Law',3],
  ['LAW301','Agricultural Law and Reforms',3],
  ['LAW302','Criminal Law',3],
  ['LAW303','Company Law',3],
  ['LAW304','International Law (Public)',3],
  ['LAW305','Principles of Civil Procedure',3],
  ['LAW306','Evidence',3],
  ['LAW307','Laws on Insurance',3],
  ['LAW308','Criminal Procedure',3],
  ['LAW322','Intellectual Property Law',3],
  ['LAW331','Banking and Securities Law',3],
  ['LAW332','Laws on Foreign Exchange, Investment and Anti-Money Laundering',3],
  ['LAW342','Legal Systems and Institutions',3],
  ['LAW344','Alternative Dispute Resolution (ADR) and Arbitration',3],
  ['LAW346','Environmental Law',3],
  ['LAW351','Hindu Law and Succession',3],
  ['LAW391','Seminar Course',3],
  ['LAW401','Conveyancing and Legal Writings',3],
  ['LAW402','Legal Research and Methodology',3],
  ['LAW403','Moot Court Sessions',3],
  ['LAW404','Law of Trusts and Codicils',3],
  ['LAW423','Maritime Law and Carriers',3],
  ['LAW425','Cyber Law',3],
  ['LAW434','Taxation Law Including Customs and VAT',3],
  ['LAW435','Labour and Industrial Law',3],
  ['LAW447','Human Rights',3],
  // ── Pharmacy — New Syllabus (PHB) ─────────────────
  // Theory courses (3 credits each)
  ['PHB101','Inorganic Chemistry I',3],
  ['PHB102','Pharmaceutical Microbiology I',3],
  ['PHB102L','Pharmaceutical Microbiology I Lab',1],
  ['PHB103','Physiology & Anatomy I',3],
  ['PHB103L','Physiology & Anatomy I Lab',1],
  ['PHB104','Organic Chemistry I',3],
  ['PHB104L','Organic Chemistry I Lab',1],
  ['PHB105','Inorganic Chemistry II',3],
  ['PHB105L','Inorganic Chemistry Lab',1],
  ['PHB106','Physical Pharmacy I',3],
  ['PHB106L','Physical Pharmacy I Lab',1],
  ['PHB107','Mathematics and Elementary Statistics',3],
  ['PHB107L','Mathematics and Elementary Statistics Lab',1],
  ['PHB108','Pharmaceutical Microbiology II',3],
  ['PHB109','Organic Chemistry II',3],
  ['PHB109L','Organic Chemistry II Lab',1],
  ['PHB110','Oral Assessment I',1],
  ['PHB201','Physiology & Anatomy II',3],
  ['PHB201L','Physiology & Anatomy II Lab',1],
  ['PHB202','Pharmacognosy & Herbal Medicine',3],
  ['PHB202L','Pharmacognosy & Herbal Medicine Lab',1],
  ['PHB203','Physical Pharmacy II',3],
  ['PHB203L','Physical Pharmacy II Lab',1],
  ['PHB204','Pharmaceutical Analysis I',3],
  ['PHB204L','Pharmaceutical Analysis I Lab',1],
  ['PHB205','Pharmacology I',3],
  ['PHB205L','Pharmacology I Lab',1],
  ['PHB206','Pharmaceutical Calculations',3],
  ['PHB207','Oral Assessment II',1],
  ['PHB301','Biochemistry and Molecular Biology',3],
  ['PHB301L','Biochemistry and Molecular Biology Lab',1],
  ['PHB302','Pharmaceutical Technology I',3],
  ['PHB302L','Pharmaceutical Technology I Lab',1],
  ['PHB303','Pharmaceutical Engineering',3],
  ['PHB304','Medicinal Chemistry I',3],
  ['PHB304L','Medicinal Chemistry I Lab',1],
  ['PHB305','Pharmacology II',3],
  ['PHB305L','Pharmacology II Lab',1],
  ['PHB306','Pathology',3],
  ['PHB307','Pharmaceutical Analysis II',3],
  ['PHB307L','Pharmaceutical Analysis II Lab',1],
  ['PHB308','Pharmaceutical Technology II',3],
  ['PHB308L','Pharmaceutical Technology II Lab',1],
  ['PHB309','Medicinal Chemistry II',3],
  ['PHB309L','Medicinal Chemistry II Lab',1],
  ['PHB310','Biopharmaceutics & Pharmacokinetics I',3],
  ['PHB310L','Biopharmaceutics & Pharmacokinetics I Lab',1],
  ['PHB311','Cosmetology',3],
  ['PHB311L','Cosmetology Lab',1],
  ['PHB313','Oral Assessment III',1],
  ['PHB401','Pharmaceutical Analysis III',3],
  ['PHB402','Biopharmaceutics & Pharmacokinetics II',3],
  ['PHB402L','Biopharmaceutics & Pharmacokinetics II Lab',1],
  ['PHB404','Marketing',3],
  ['PHB405','Pharmaceutical Biotechnology',3],
  ['PHB406','Project',0],
  ['PHB407','Pharmaceutical Technology III',3],
  ['PHB407L','Pharmaceutical Technology III Lab',1],
  ['PHB408','Clinical Pharmacology and Toxicology',3],
  ['PHB412','Pharmaceutical Management',3],
  // ── Pharmacy — Old Syllabus (PHR) — backlog only ──
  ['PHR405','Clinical Pharmacy',3],
  ['PHR410','Advanced Pharmaceutical Analysis',3],
  ['PHR411','Pharmacology III',3],
  ['PHR412','Hospital and Community Pharmacy',3],
  ['PHR413','Pharmaceutical Regulatory Affairs',3],
  ['PHR414','Project',3],
  ['PHR415','Oral Assessment IV',1],
  ['PHR416','Pharmacology III Lab',1],
  // ── Architecture ─────────────────────────────────
  ['ARC101','Design I: Basic Design',4.5],
  ['ARC102','Design II',4.5],
  ['ARC111','Graphic Communication I',3],
  ['ARC112','Graphic Communication II',1.5],
  ['ARC113','CAD: Computer Aided Design',1.5],
  ['ARC121','Introduction to Architecture',2],
  ['ARC122','History of Art and Architecture I',2],
  ['ARC123','History of Art and Architecture II',2],
  ['ARC201','Design III',6],
  ['ARC202','Design IV',6],
  ['ARC214','Computer Graphics',1.5],
  ['ARC224','History of Art and Architecture III',2],
  ['ARC225','History of Art and Architecture IV',2],
  ['ARC231','Concepts in Planning',2],
  ['ARC232','Urbanism',2],
  ['ARC241','Construction I',2],
  ['ARC242','Construction II',2],
  ['ARC251','Design with Climate',2],
  ['ARC252','Lighting and Acoustical Design',2],
  ['ARC291','Sculpture',2],
  ['ARC293','Music Appreciation',2],
  ['ARC294','Photography',2],
  ['ARC301','Design V',8],
  ['ARC302','Design VI',8],
  ['ARC311','Working Drawings I',1.5],
  ['ARC312','Working Drawings II: Production Drawings',1.5],
  ['ARC315','Digital Visualization',1.5],
  ['ARC326','History of Art and Architecture V',2],
  ['ARC327','History of Bengal Art and Architecture',2],
  ['ARC331','Urban Design',2],
  ['ARC343','Technology and Construction',2],
  ['ARC394','Contemporary South Asian Architecture',2],
  ['ARC401','Design VII',10],
  ['ARC402','Design VIII',10],
  ['ARC411','Interior Design',1.5],
  ['ARC412','Landscape Design',2],
  ['ARC413','Estimation',1.5],
  ['ARC431','Rural Architecture',2],
  ['ARC432','Housing and Development',2],
  ['ARC441','Specifications',2],
  ['ARC452','Design for the Environment',2],
  ['ARC491','Architectural Conservation',2],
  ['ARC501','Design IX',12],
  ['ARC502','Design X',12],
  ['ARC503','Design Studio X (Alternative to ARC 502)',12],
  ['ARC511','Seminar I',1.5],
  ['ARC512','Seminar II',1.5],
  ['ARC522','Research Methods',2],
  ['ARC541','Professional Practice',2],
  // ── Biotechnology ─────────────────────────────────
  ['BIO101','Introduction to Biology',3],
  ['BIO102','Cell Biology',3],
  ['BIO201','Genetics',3],
  ['BIO202','Molecular Biology',3],
  ['BIO203','Biochemistry for Biotech',3],
  ['BIO204','Microbiology for Biotech',3],
  ['BIO301','Genetic Engineering',3],
  ['BIO302','Immunology',3],
  ['BIO303','Bioinformatics',3],
  ['BIO401','Biotechnology Thesis',6],
  // ── Chemical Engineering ──────────────────────────
  ['CHE101','Introduction to Chemical Engineering',3],
  ['CHE102','Chemistry I',3],
  ['CHE103','Chemistry II',3],
  ['CHE201','Chemical Engineering Thermodynamics',3],
  ['CHE202','Fluid Mechanics',3],
  ['CHE203','Heat Transfer',3],
  ['CHE301','Mass Transfer',3],
  ['CHE302','Chemical Reaction Engineering',3],
  ['CHE303','Process Control',3],
  ['CHE401','Plant Design',3],
  ['CHE402','Chemical Engineering Thesis',6],
];

_CATALOG.forEach(([code, name, credits]) => {
  const full = `${name} (${code})`;
  COURSE_DB[code] = { code, name, credits, full };
});

Object.values(DEPARTMENTS).forEach(dept => {
  dept.presets.forEach(sem => {
    sem.courses.forEach(c => {
      const match = c.name.match(/\(([A-Z]{2,4}\d{3}[A-Z]?)\)$/);
      const code  = match ? match[1] : '';
      const name  = c.name.replace(/\s*\([^)]+\)$/, '').trim();
      if (code && !COURSE_DB[code]) {
        COURSE_DB[code] = { code, name, credits: c.credits, full: c.name };
      }
    });
  });
});

export const ALL_COURSES = Object.values(COURSE_DB).sort((a,b) => a.code.localeCompare(b.code));