import { DEPARTMENTS } from './departments.js';

export const COURSE_DB = {};

const _CATALOG = [
  // ── GED / Common ─────────────────────────────────
  ['BNG103','Bangla Language and Literature',3],
  ['EMB101','Emergence of Bangladesh',3],
  ['ENG101','Fundamentals of English',3],
  ['ENG102','English Composition I',3],
  ['HUM103','Ethics and Culture',3],
  ['MAT092','Remedial Course in Mathematics',0],
  ['PHY111','Principles of Physics I',3],
  ['PHY112','Principles of Physics II',3],
  ['MAT110','Mathematics I: Differential Calculus & Coordinate Geometry',3],
  ['MAT120','Mathematics II: Integral Calculus & Differential Equations',3],
  ['MAT215','Mathematics III: Complex Variables & Laplace Transformations',3],
  ['STA201','Elements of Statistics and Probability',3],
  ['SOC101','Introduction to Sociology',3],
  ['POL101','Introduction to Political Science',3],
  ['ECO101','Principles of Microeconomics',3],
  ['ECO102','Principles of Macroeconomics',3],
  // ── CSE ──────────────────────────────────────────
  ['CSE101','Introduction to Computer Science',3],
  ['CSE103','Introduction to Computing',3],
  ['CSE110','Programming Language I',3],
  ['CSE111','Programming Language-II',3],
  ['CSE220','Data Structures',3],
  ['CSE221','Algorithms',3],
  ['CSE230','Discrete Mathematics',3],
  ['CSE250','Circuits and Electronics',3],
  ['CSE260','Digital Logic Design',3],
  ['CSE310','Object Oriented Programming',3],
  ['CSE320','Data Communications',3],
  ['CSE321','Operating Systems',3],
  ['CSE330','Numerical Methods',3],
  ['CSE331','Automata and Computability',3],
  ['CSE340','Computer Architecture',3],
  ['CSE341','Microprocessors',3],
  ['CSE350','Digital Electronics and Pulse Techniques',3],
  ['CSE360','Computer Interfacing',3],
  ['CSE370','Database Systems',3],
  ['CSE390','Technical Communication',3],
  ['CSE391','Programming for the Internet',3],
  ['CSE400','Project & Thesis',4],
  ['CSE402','Optimization',3],
  ['CSE420','Compiler Design',3],
  ['CSE421','Computer Networks',3],
  ['CSE422','Artificial Intelligence',3],
  ['CSE423','Computer Graphics',3],
  ['CSE424','Pattern Recognition',3],
  ['CSE425','Neural Networks',3],
  ['CSE426','Advanced Algorithms',3],
  ['CSE427','Machine Learning',3],
  ['CSE428','Image Processing',3],
  ['CSE437','Data Science: Coding with Real World Data',3],
  ['CSE440','Natural Language Processing II',3],
  ['CSE443','Bioinformatics I',3],
  ['CSE446','Blockchain and Cryptocurrencies',3],
  ['CSE447','Cryptography and Cryptoanalysis',3],
  ['CSE449','Parallel, Distributed, and High-Performance Computing (HPC)',3],
  ['CSE460','VLSI Design',3],
  ['CSE461','Introduction to Robotics',3],
  ['CSE463','Computer Vision: Fundamentals and Applications',3],
  ['CSE470','Software Engineering',3],
  ['CSE471','System Analysis and Design',3],
  ['CSE472','Human Computer Interface',3],
  ['CSE481','Quantum Computing I',3],
  ['CSE482','Quantum Computing II',3],
  ['CSE489','Android App Development',3],
  ['CSE490A','Gamification: Engineering User Engagement',3],
  ['CSE490B','Introduction to Cybersecurity',3],
  ['CSE490C','Quantum Computing III',3],
  ['CSE490D','Introduction to Football Data and Analytics',3],
  // ── EEE ──────────────────────────────────────────
  ['EEE101','Electrical Circuits I',3],
  ['EEE103','Computer Programming',3],
  ['EEE203','Electrical Circuits II',3],
  ['EEE205','Electronic Circuits I',3],
  ['EEE221','Energy Conversion I',3],
  ['EEE241','Electromagnetic Waves and Fields',3],
  ['EEE243','Signals and Systems',3],
  ['EEE282','Numerical Techniques',3],
  ['EEE283','Digital Logic Design',3],
  ['EEE301','Digital Electronics',3],
  ['EEE302','Digital Electronics Laboratory',1.5],
  ['EEE305','Control Systems',3],
  ['EEE308','Electronic Circuits II',3],
  ['EEE309','Semiconductor Device Physics',3],
  ['EEE321','Power System I',3],
  ['EEE341','Introduction to Communication Engineering',3],
  ['EEE343','Digital Signal Processing',3],
  ['EEE345','Electrical Services',3],
  ['EEE359','Engineering Project Management',3],
  ['EEE361','Data Communications',3],
  ['EEE365','Microprocessors',3],
  ['EEE366','Microprocessors Laboratory',1.5],
  ['EEE369','Professional Practice, Engineers and Society',3],
  ['EEE373','Embedded System Design',3],
  ['EEE382','Modelling and Simulation',3],
  ['EEE383','Electronic System Design',3],
  ['EEE384','Electrical Service Design',3],
  ['EEE385','Machine Learning',3],
  ['EEE403','Properties of Electronic Materials',3],
  ['EEE410','Computer Architecture',3],
  ['EEE411','VLSI Design',3],
  ['EEE412','VLSI Design Laboratory',1.5],
  ['EEE415','Analog Integrated Circuit Design',3],
  ['EEE421','Power Electronics',3],
  ['EEE433','Power System II',3],
  ['EEE435','Renewable Energy Systems',3],
  ['EEE445','Digital Communications',3],
  ['EEE465','Computer Networks',3],
  ['EEE472','Artificial Intelligence',3],
  ['EEE474','Neural Networks',3],
  ['EEE476','Image Processing',3],
  ['EEE498','Directed Research',3],
  // ── BBA ──────────────────────────────────────────
  ['ACC101','Introduction to Financial Accounting',3],
  ['ACC201','Introduction to Management Accounting',3],
  ['ACC301','Intermediate Accounting I',3],
  ['ACC302','Intermediate Accounting II',3],
  ['ACC303','Advanced Accounting',3],
  ['ACC311','Cost and Management Accounting',3],
  ['ACC401','Auditing and Assurance',3],
  ['ACC402','Taxation',3],
  ['BUS101','Introduction to Business',3],
  ['BUS102','Business Communication',3],
  ['BUS201','Business Statistics',3],
  ['BUS202','Business Mathematics',3],
  ['BUS211','Business Law',3],
  ['BUS301','Entrepreneurship and Innovation',3],
  ['BUS302','Research Methods in Business',3],
  ['BUS401','Business Policy and Strategy',3],
  ['BUS499','BBA Internship',3],
  ['ECO201','Intermediate Microeconomics',3],
  ['ECO211','Intermediate Macroeconomics',3],
  ['ECO212','Bangladesh Economy',3],
  ['ECO301','Managerial Economics',3],
  ['ECO311','International Economics',3],
  ['ECO321','Development Economics',3],
  ['ECO331','Monetary Economics',3],
  ['FIN201','Principles of Finance',3],
  ['FIN301','Financial Management',3],
  ['FIN302','Investment Analysis and Portfolio Management',3],
  ['FIN303','Financial Markets and Institutions',3],
  ['FIN311','Corporate Finance',3],
  ['FIN312','International Finance',3],
  ['FIN401','Advanced Financial Management',3],
  ['HRM301','Human Resource Management',3],
  ['HRM302','Organizational Behavior',3],
  ['HRM303','Compensation Management',3],
  ['HRM401','Strategic HRM',3],
  ['MGT101','Principles of Management',3],
  ['MGT201','Organizational Theory and Design',3],
  ['MGT301','Operations Management',3],
  ['MGT302','Project Management',3],
  ['MGT401','Supply Chain Management',3],
  ['MKT201','Principles of Marketing',3],
  ['MKT301','Consumer Behavior',3],
  ['MKT302','Marketing Research',3],
  ['MKT303','Advertising and Promotion',3],
  ['MKT401','Strategic Marketing',3],
  ['MKT402','Digital Marketing',3],
  ['MKT403','International Marketing',3],
  // ── English ───────────────────────────────────────
  ['ENG111','Introduction to Literature',3],
  ['ENG121','Introduction to Linguistics',3],
  ['ENG201','British Literature I',3],
  ['ENG202','British Literature II',3],
  ['ENG211','American Literature',3],
  ['ENG212','World Literature in English',3],
  ['ENG221','Introduction to Language Studies',3],
  ['ENG222','Phonetics and Phonology',3],
  ['ENG223','Morphology and Syntax',3],
  ['ENG224','Semantics and Pragmatics',3],
  ['ENG225','Sociolinguistics',3],
  ['ENG226','Psycholinguistics',3],
  ['ENG301','Literary Theory and Criticism',3],
  ['ENG302','Postcolonial Literature',3],
  ['ENG303','South Asian Literature',3],
  ['ENG304','Bangladesh Literature in English',3],
  ['ENG311','Applied Linguistics',3],
  ['ENG312','Language Acquisition',3],
  ['ENG313','Discourse Analysis',3],
  ['ENG314','English for Specific Purposes',3],
  ['ENG401','Advanced Literary Studies',3],
  ['ENG411','Research Methods',3],
  ['ENG412','ELT Methodology',3],
  ['ENG421','Creative Writing',3],
  ['ENG422','Translation Studies',3],
  ['ENG431','English Thesis',6],
  // ── Law ───────────────────────────────────────────
  ['LAW101','Legal System of Bangladesh',3],
  ['LAW111','Law of Contract',3],
  ['LAW201','Constitutional Law',3],
  ['LAW211','Law of Tort',3],
  ['LAW221','Criminal Law',3],
  ['LAW222','Evidence Law',3],
  ['LAW301','Administrative Law',3],
  ['LAW302','Company Law',3],
  ['LAW311','Civil Procedure Code',3],
  ['LAW312','Criminal Procedure Code',3],
  ['LAW321','Land Law',3],
  ['LAW322','Family Law',3],
  ['LAW331','International Law',3],
  ['LAW332','Intellectual Property Law',3],
  ['LAW333','Environmental Law',3],
  ['LAW401','Jurisprudence',3],
  ['LAW411','Arbitration and Alternative Dispute Resolution',3],
  ['LAW412','Banking Law',3],
  ['LAW421','Tax Law',3],
  ['LAW422','Labour Law',3],
  ['LAW431','Moot Court and Legal Drafting',3],
  ['LAW432','Human Rights Law',3],
  // ── Pharmacy — New Syllabus (PHB) ─────────────────
  // Theory courses (3 credits each)
  ['PHB101','Inorganic Chemistry I',3],
  ['PHB102','Pharmaceutical Microbiology I',3],
  ['PHB102L','Pharmaceutical Microbiology I Lab',1],
  ['PHB103','Physiology & Anatomy I',3],
  ['PHB103L','Physiology & Anatomy I Lab',1],
  ['PHB104','Organic Chemistry I',3],
  ['PHB104L','Organic Chemistry I Lab',1],
  ['PHB105','Inorganic Chemistry II',3],
  ['PHB105L','Inorganic Chemistry Lab',1],
  ['PHB106','Physical Pharmacy I',3],
  ['PHB106L','Physical Pharmacy I Lab',1],
  ['PHB107','Mathematics and Elementary Statistics',3],
  ['PHB107L','Mathematics and Elementary Statistics Lab',1],
  ['PHB108','Pharmaceutical Microbiology II',3],
  ['PHB109','Organic Chemistry II',3],
  ['PHB109L','Organic Chemistry II Lab',1],
  ['PHB110','Oral Assessment I',1],
  ['PHB201','Physiology & Anatomy II',3],
  ['PHB201L','Physiology & Anatomy II Lab',1],
  ['PHB202','Pharmacognosy & Herbal Medicine',3],
  ['PHB202L','Pharmacognosy & Herbal Medicine Lab',1],
  ['PHB203','Physical Pharmacy II',3],
  ['PHB203L','Physical Pharmacy II Lab',1],
  ['PHB204','Pharmaceutical Analysis I',3],
  ['PHB204L','Pharmaceutical Analysis I Lab',1],
  ['PHB205','Pharmacology I',3],
  ['PHB205L','Pharmacology I Lab',1],
  ['PHB206','Pharmaceutical Calculations',3],
  ['PHB207','Oral Assessment II',1],
  ['PHB301','Biochemistry and Molecular Biology',3],
  ['PHB301L','Biochemistry and Molecular Biology Lab',1],
  ['PHB302','Pharmaceutical Technology I',3],
  ['PHB302L','Pharmaceutical Technology I Lab',1],
  ['PHB303','Pharmaceutical Engineering',3],
  ['PHB304','Medicinal Chemistry I',3],
  ['PHB304L','Medicinal Chemistry I Lab',1],
  ['PHB305','Pharmacology II',3],
  ['PHB305L','Pharmacology II Lab',1],
  ['PHB306','Pathology',3],
  ['PHB307','Pharmaceutical Analysis II',3],
  ['PHB307L','Pharmaceutical Analysis II Lab',1],
  ['PHB308','Pharmaceutical Technology II',3],
  ['PHB308L','Pharmaceutical Technology II Lab',1],
  ['PHB309','Medicinal Chemistry II',3],
  ['PHB309L','Medicinal Chemistry II Lab',1],
  ['PHB310','Biopharmaceutics & Pharmacokinetics I',3],
  ['PHB310L','Biopharmaceutics & Pharmacokinetics I Lab',1],
  ['PHB311','Cosmetology',3],
  ['PHB311L','Cosmetology Lab',1],
  ['PHB313','Oral Assessment III',1],
  ['PHB401','Pharmaceutical Analysis III',3],
  ['PHB402','Biopharmaceutics & Pharmacokinetics II',3],
  ['PHB402L','Biopharmaceutics & Pharmacokinetics II Lab',1],
  ['PHB404','Marketing',3],
  ['PHB405','Pharmaceutical Biotechnology',3],
  ['PHB406','Project',0],
  ['PHB407','Pharmaceutical Technology III',3],
  ['PHB407L','Pharmaceutical Technology III Lab',1],
  ['PHB408','Clinical Pharmacology and Toxicology',3],
  ['PHB412','Pharmaceutical Management',3],
  // ── Pharmacy — Old Syllabus (PHR) — backlog only ──
  ['PHR405','Clinical Pharmacy',3],
  ['PHR410','Advanced Pharmaceutical Analysis',3],
  ['PHR411','Pharmacology III',3],
  ['PHR412','Hospital and Community Pharmacy',3],
  ['PHR413','Pharmaceutical Regulatory Affairs',3],
  ['PHR414','Project',3],
  ['PHR415','Oral Assessment IV',1],
  ['PHR416','Pharmacology III Lab',1],
  // ── Architecture ─────────────────────────────────
  ['ARC101','Design I: Basic Design',4.5],
  ['ARC102','Design II',4.5],
  ['ARC111','Graphic Communication I',3],
  ['ARC112','Graphic Communication II',1.5],
  ['ARC113','CAD: Computer Aided Design',1.5],
  ['ARC121','Introduction to Architecture',2],
  ['ARC122','History of Art and Architecture I',2],
  ['ARC123','History of Art and Architecture II',2],
  ['ARC201','Design III',6],
  ['ARC202','Design IV',6],
  ['ARC214','Computer Graphics',1.5],
  ['ARC224','History of Art and Architecture III',2],
  ['ARC225','History of Art and Architecture IV',2],
  ['ARC231','Concepts in Planning',2],
  ['ARC232','Urbanism',2],
  ['ARC241','Construction I',2],
  ['ARC242','Construction II',2],
  ['ARC251','Design with Climate',2],
  ['ARC252','Lighting and Acoustical Design',2],
  ['ARC291','Sculpture',2],
  ['ARC293','Music Appreciation',2],
  ['ARC294','Photography',2],
  ['ARC301','Design V',8],
  ['ARC302','Design VI',8],
  ['ARC311','Working Drawings I',1.5],
  ['ARC312','Working Drawings II: Production Drawings',1.5],
  ['ARC315','Digital Visualization',1.5],
  ['ARC326','History of Art and Architecture V',2],
  ['ARC327','History of Bengal Art and Architecture',2],
  ['ARC331','Urban Design',2],
  ['ARC343','Technology and Construction',2],
  ['ARC394','Contemporary South Asian Architecture',2],
  ['ARC401','Design VII',10],
  ['ARC402','Design VIII',10],
  ['ARC411','Interior Design',1.5],
  ['ARC412','Landscape Design',2],
  ['ARC413','Estimation',1.5],
  ['ARC431','Rural Architecture',2],
  ['ARC432','Housing and Development',2],
  ['ARC441','Specifications',2],
  ['ARC452','Design for the Environment',2],
  ['ARC491','Architectural Conservation',2],
  ['ARC501','Design IX',12],
  ['ARC502','Design X',12],
  ['ARC503','Design Studio X (Alternative to ARC 502)',12],
  ['ARC511','Seminar I',1.5],
  ['ARC512','Seminar II',1.5],
  ['ARC522','Research Methods',2],
  ['ARC541','Professional Practice',2],
  // ── Biotechnology ─────────────────────────────────
  ['BIO101','Introduction to Biology',3],
  ['BIO102','Cell Biology',3],
  ['BIO201','Genetics',3],
  ['BIO202','Molecular Biology',3],
  ['BIO203','Biochemistry for Biotech',3],
  ['BIO204','Microbiology for Biotech',3],
  ['BIO301','Genetic Engineering',3],
  ['BIO302','Immunology',3],
  ['BIO303','Bioinformatics',3],
  ['BIO401','Biotechnology Thesis',6],
  // ── Chemical Engineering ──────────────────────────
  ['CHE101','Introduction to Chemical Engineering',3],
  ['CHE102','Chemistry I',3],
  ['CHE103','Chemistry II',3],
  ['CHE201','Chemical Engineering Thermodynamics',3],
  ['CHE202','Fluid Mechanics',3],
  ['CHE203','Heat Transfer',3],
  ['CHE301','Mass Transfer',3],
  ['CHE302','Chemical Reaction Engineering',3],
  ['CHE303','Process Control',3],
  ['CHE401','Plant Design',3],
  ['CHE402','Chemical Engineering Thesis',6],
];

_CATALOG.forEach(([code, name, credits]) => {
  const full = `${name} (${code})`;
  COURSE_DB[code] = { code, name, credits, full };
});

Object.values(DEPARTMENTS).forEach(dept => {
  dept.presets.forEach(sem => {
    sem.courses.forEach(c => {
      const match = c.name.match(/\(([A-Z]{2,4}\d{3}[A-Z]?)\)$/);
      const code  = match ? match[1] : '';
      const name  = c.name.replace(/\s*\([^)]+\)$/, '').trim();
      if (code && !COURSE_DB[code]) {
        COURSE_DB[code] = { code, name, credits: c.credits, full: c.name };
      }
    });
  });
});

export const ALL_COURSES = Object.values(COURSE_DB).sort((a,b) => a.code.localeCompare(b.code));