// tests/pdfReportDraw.test.js — smoke tests for the PDF drawing layer (#325)
// over a recording fake document: the walk completes, key strings land on the
// page, pagination kicks in for long reports, and save gets the legacy name.

import test from 'node:test';
import assert from 'node:assert/strict';

import { buildPdfReport } from '../src/features/calculator/pdfReport.ts';
import { drawPdfReport } from '../src/features/calculator/pdfReportDraw.ts';

function recorder() {
  const calls = { text: [], pages: 1, saved: null, images: 0 };
  const noop = () => {};
  return {
    calls,
    doc: {
      setFillColor: noop,
      setDrawColor: noop,
      setTextColor: noop,
      setFontSize: noop,
      setFont: noop,
      setLineWidth: noop,
      rect: noop,
      roundedRect: noop,
      line: noop,
      text: (str) => calls.text.push(str),
      addImage: () => {
        calls.images += 1;
      },
      addPage: () => {
        calls.pages += 1;
      },
      save: (name) => {
        calls.saved = name;
      },
    },
  };
}

const NOW = new Date(2026, 6, 3, 19, 45);

function smallState() {
  return {
    semesters: [
      {
        id: 1,
        name: 'Fall 2024 (1st Semester)',
        running: false,
        courses: [
          { name: 'Programming Language I (CSE110)', credits: 3, grade: 'A' },
          { name: 'Transfer (CSE101)', credits: 3, grade: 'F(NT)' },
        ],
      },
      {
        id: 0,
        name: 'Past Semesters',
        summary: true,
        summaryCGPA: 3.5,
        summaryCredits: 30,
        summaryAttempted: 33,
        courses: [],
        running: false,
      },
    ],
    startSeason: 'Fall',
    startYear: '2024',
    currentDept: 'CSE',
  };
}

test('the walk draws the key content and saves under the legacy filename', () => {
  const { doc, calls } = recorder();
  drawPdfReport(doc, buildPdfReport(smallState(), NOW));

  const all = calls.text.join('\n');
  assert.match(all, /CGPA Report/);
  assert.match(all, /B\.Sc\. in Computer Science and Engineering \(CSE\)/);
  assert.match(all, /Fall 2024 \| 1st Semester/);
  assert.match(all, /Programming Language I \(CSE110\)/);
  assert.match(all, /No Transfer/); // the F(NT) note
  assert.match(all, /Past Semesters Summary/);
  assert.match(all, /CGPA 3\.50   ·   Earned 30 cr   ·   Attempted 33 cr/);
  assert.match(all, /CUMULATIVE GPA/);
  assert.match(all, /Generated by Shohoj · BRAC University CGPA Calculator/);
  assert.equal(calls.saved, 'BRACU_CGPA_Report_Shohoj.pdf');
  assert.equal(calls.pages, 1);
  assert.equal(calls.images, 2); // header + footer logo
});

test('a long report paginates with the continued-page header', () => {
  const semesters = Array.from({ length: 12 }, (_, s) => ({
    id: s + 1,
    name: `Semester ${s + 1}`,
    running: false,
    courses: Array.from({ length: 6 }, (_, c) => ({
      name: `Course ${s + 1}.${c + 1} (CSE1${String(10 + c)})`,
      credits: 3,
      grade: 'B',
    })),
  }));
  const { doc, calls } = recorder();
  drawPdfReport(
    doc,
    buildPdfReport({ semesters, startSeason: '', startYear: '', currentDept: '' }, NOW),
  );

  assert.ok(calls.pages > 1, `expected multiple pages, got ${calls.pages}`);
  assert.ok(calls.text.filter((t) => t === 'Shohoj CGPA Report (continued)').length >= 1);
  assert.equal(calls.saved, 'BRACU_CGPA_Report_Shohoj.pdf');
});

test('an addImage failure falls back to the drawn logo without aborting', () => {
  const { doc, calls } = recorder();
  doc.addImage = () => {
    throw new Error('unsupported');
  };
  drawPdfReport(doc, buildPdfReport(smallState(), NOW));
  assert.equal(calls.saved, 'BRACU_CGPA_Report_Shohoj.pdf'); // walk completed
});
