// e2e-shell/calculator-pdf-export.spec.js
//
// #325: PDF export on the React Router shell's /calculator route, against the
// built dist-shell/ output. window.jspdf is stubbed via addInitScript with a
// recording constructor (the on-demand loader short-circuits on the global),
// so the tests assert what the report drew and saved; the failure test blocks
// the CDN and expects the legacy error copy as a toast.

import { expect, test } from '../e2e-support/authFixture.js';

function stubJsPdf(page) {
  return page.addInitScript(() => {
    window.__pdfCalls = { text: [], saved: null, pages: 1 };
    const calls = window.__pdfCalls;
    const noop = () => {};
    window.jspdf = {
      jsPDF: class {
        constructor() {
          this.setFillColor = noop;
          this.setDrawColor = noop;
          this.setTextColor = noop;
          this.setFontSize = noop;
          this.setFont = noop;
          this.setLineWidth = noop;
          this.rect = noop;
          this.roundedRect = noop;
          this.line = noop;
          this.addImage = noop;
          this.text = (str) => calls.text.push(String(str));
          this.addPage = () => {
            calls.pages += 1;
          };
          this.save = (name) => {
            calls.saved = name;
          };
        }
      },
    };
  });
}

async function openWithDemo(page) {
  await page.goto('/app/index.html', { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => localStorage.clear());
  await page.getByRole('link', { name: 'Calculator', exact: true }).click();
  await page.locator('#semestersContainer').getByRole('button', { name: 'Try Demo Mode' }).click();
}

test('exporting demo data draws the report and saves the legacy filename', async ({ page }) => {
  await stubJsPdf(page);
  await openWithDemo(page);

  await page.locator('.footer-btn-group').getByRole('button', { name: '⬇ Export PDF' }).click();

  await expect
    .poll(async () => page.evaluate(() => window.__pdfCalls.saved))
    .toBe('BRACU_CGPA_Report_Shohoj.pdf');

  const drawn = await page.evaluate(() => window.__pdfCalls.text.join('\n'));
  expect(drawn).toContain('CGPA Report');
  // Demo data: CSE dept, 3.50 CGPA over two semesters.
  expect(drawn).toContain('B.Sc. in Computer Science and Engineering (CSE)');
  expect(drawn).toContain('3.50');
  expect(drawn).toContain('Fall 2024');
  expect(drawn).toContain('Spring 2025');
  expect(drawn).toContain('Programming Language I (CSE110)');
  expect(drawn).toContain('Distinction'); // the standing stat
  expect(drawn).toContain('Generated by Shohoj · BRAC University CGPA Calculator');
});

test('a blocked CDN surfaces the legacy error copy as a toast', async ({ page }) => {
  // No stub — and the pinned CDN is unreachable.
  await page.route('https://cdnjs.cloudflare.com/**', (route) => route.abort());
  await openWithDemo(page);

  await page.locator('.footer-btn-group').getByRole('button', { name: '⬇ Export PDF' }).click();

  await expect(page.getByText('PDF library not loaded. Please check your connection.')).toBeVisible();
});
